name: build

on:
  push:
    branches:
      - main
      - release-*
  pull_request:
  workflow_dispatch:

concurrency: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Essentials
        run: sudo apt-get install build-essential

      - name: Ninja
        run: sudo apt-get install ninja-build

      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Generate
        run: cmake . -B build -G Ninja
        
      - name: Build
        run: cmake --build build
